server:
  port: 8083

spring:
  application:
    name: enrollment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/easy_hiring_db
    username: postgres
    password: Vinay@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
